name: 'Kilnfi_connect_rs::Release'

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:

  release:
    permissions:
      contents: write 
      attestations: write
      id-token: write
    name: 'release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: 'Install Rust toolchain'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85.1
      - name: 'release'
        if: contains(github.ref, '-') == false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        uses: 'katyo/publish-crates@v2'
        with:
          registry-token: ${{ env.CARGO_REGISTRY_TOKEN }}
      - name: 'write release notes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: docker://antonyurchenko/git-release:latest