name: Kilnfi_connect_rs::Release

on:
  workflow_dispatch:
    
permissions:
  pull-requests: write
  contents: write

jobs:

  release-plz:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}  
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ env.CARGO_REGISTRY_TOKEN }}