name: Kilnfi_connect_rs::Test

on:
  workflow_dispatch:
    
jobs:

  test:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: test
        env:
          KILN_API_TOKEN: ${{ secrets.KILN_API_TOKEN }}
        run: cargo test